In [2]:
import numpy as np

In [3]:
mat = np.arange(0,100).reshape(10,10)

In [5]:
mat.shape

(10, 10)

In [6]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
row = 0
column = 1

In [9]:
mat[row,column]

1

In [10]:
mat[4,6]#[4->row,6->column]----> bu sekilde row ve columun yerini arrayde alabiliyoruz

46

In [11]:
mat[:,1]#---> butun rowlar ancak sadece 1. column

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [12]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [13]:
mat[:,1].reshape(1,10)

array([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [14]:
mat[2,:] #rowun tamamini aldik

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [18]:
mat[0:3,0:3]=0

In [19]:
mynewmat = mat.copy()

In [20]:
mynewmat[0:6,:]=999

In [21]:
mynewmat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])