In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt("Computer-Vision-with-Python/DATA/bank_note_data.txt",delimiter = ',')

In [3]:
data #if last index of array is 0 it will be forgery and if it is 1  it will be authentic

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y=labels

In [9]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.33,random_state=42)

In [12]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
scaler_object = MinMaxScaler()

In [15]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [16]:
scaled_X_train = scaler_object.transform(X_train)

In [17]:
scaled_X_test = scaler_object.transform(X_test)

In [18]:
scaled_X_train.max()

1.0000000000000002

In [20]:
from keras.models import Sequential
from keras.layers import Dense

In [21]:
model = Sequential()
model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [22]:
model.compile(loss ='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [23]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 0.7190 - acc: 0.5495
Epoch 2/50
 - 0s - loss: 0.6740 - acc: 0.5495
Epoch 3/50
 - 0s - loss: 0.6524 - acc: 0.5495
Epoch 4/50
 - 0s - loss: 0.6404 - acc: 0.5495
Epoch 5/50
 - 0s - loss: 0.6319 - acc: 0.5495
Epoch 6/50
 - 0s - loss: 0.6238 - acc: 0.5495
Epoch 7/50
 - 0s - loss: 0.6152 - acc: 0.5495
Epoch 8/50
 - 0s - loss: 0.6061 - acc: 0.5495
Epoch 9/50
 - 0s - loss: 0.5956 - acc: 0.5495
Epoch 10/50
 - 0s - loss: 0.5838 - acc: 0.5495
Epoch 11/50
 - 0s - loss: 0.5713 - acc: 0.5767
Epoch 12/50
 - 0s - loss: 0.5577 - acc: 0.6387
Epoch 13/50
 - 0s - loss: 0.5437 - acc: 0.6692
Epoch 14/50
 - 0s - loss: 0.5284 - acc: 0.7530
Epoch 15/50
 - 0s - loss: 0.5123 - acc: 0.7791
Epoch 16/50
 - 0s - loss: 0.4960 - acc: 0.8063
Epoch 17/50
 - 0s - loss: 0.4795 - acc: 0.8139
Epoch 18/50
 - 0s - loss: 0.4631 - acc: 0.8368
Epoch 19/50
 - 0s - loss: 0.4480 - acc: 0.8400
Epoch 20/50
 - 0s - loss: 0.4328 - acc: 0.8760
Epoch 21/50
 - 0s - loss: 0.4189 - acc: 0.8857
Epoch 22/50
 - 0s - lo

In [27]:
#model.predict_classes(scaled_X_test)

In [28]:
model.metrics_names

['loss', 'acc']

In [41]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score


In [30]:
prerdictions = model.predict_classes(scaled_X_test)

In [31]:
confusion_matrix(y_test,prerdictions)

array([[256,   1],
       [ 11, 185]], dtype=int64)

In [33]:
print(classification_report(y_test,prerdictions))

             precision    recall  f1-score   support

        0.0       0.96      1.00      0.98       257
        1.0       0.99      0.94      0.97       196

avg / total       0.97      0.97      0.97       453



In [35]:
model.save('mysupermodel.h5')

In [36]:
from keras.models import load_model

In [37]:
newModel = load_model('mysupermodel.h5')

In [39]:
#newModel.predict_classes(scaled_X_test)

In [42]:
accuracy_score(y_test, prerdictions)

0.9735099337748344